title: SQL cheat sheet
author:
  name: Osic Kwon
  email: osic.kwon@gmail.com

# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: https://github.com/pages-themes/dinky
remote_theme: https://github.com/pages-themes/hacker
